### ISSUE TITLE
it.json file were overwritten

### ISSUE THREAD

**Issue by Menelao147** [tessietech/localization#11]
I noticed that all the changes I made to the it.json file were removed in commit 3481b9d135bd78d64c276d36cf7dc55219cc0126.
It looks like you have added some new strings for translation, but possibly started from an outdated version of the file, which resulted in the loss of the updates I had made.

Could you please confirm if this was the case? If so, should I go ahead and restore the translations on my end, or would you be able to merge the changes and recover them?

**Comment by stx** [comment]
Thanks for the report. Should be fixed now with all of your changes included. Please re-check.
