### ISSUE TITLE
Czech Localization

### ISSUE THREAD

**Issue by budisek** [tessietech/localization#16]
Please add Czech language support. 

I can help with it if you need. 

Thanks

budis

**Comment by maja0027** [comment]
Yes, please.

**Comment by fyzik** [comment]
Yes please that would help a lot

**Comment by filipkremla** [comment]
Ano, prosím bylo by to skvělé

**Comment by MickCZ** [comment]
Where can I unduplicate ° in the cs.json translation to display only °C?

![image](https://github.com/user-attachments/assets/54fa465f-b6c3-412d-8f88-4f684ef1ae22)
![image](https://github.com/user-attachments/assets/bac1ce34-e3da-4414-ab63-67ba2a8c6763)

**Comment by budisek** [comment]
Many phrases look like google translate work. Let me know if you want a really human translation. I can help with it.

**Comment by stx** [comment]
@budisek Would love your help. This is an open source repository, so feel free to make edits to https://github.com/tessietech/localization/blob/main/cs.json.

**Comment by budisek** [comment]
Well is there any reward for translators? As far as I know, Tessie is a commercial application not open-source. So at least the Pro Subscription would be acceptable.

**Comment by budisek** [comment]
I am pretty sure that Basic plan is not free at all. 

![image](https://github.com/user-attachments/assets/eefa5ac2-e373-4f94-aacc-094d17231199)

**Comment by stx** [comment]
@budisek If you would like to join our in-house translators and own the full Czech translation, we can provide you a lifetime subscription for your work. Please email support@tessie.com.
