### ISSUE TITLE
Português, Portugal

### ISSUE THREAD

**Issue by pncsoares** [tessietech/localization#4]
Hi 👋 

First of all, congratulations on the project! I've been using Tessie since I bought my Tesla, and it has been incredibly useful.

I would like to offer my assistance in adding Portuguese language support (pt.json). As a software engineer, I can handle both the creation of the file and the translation. I would love to contribute in this way if you are interested.

Thank you,
Pedro

**Comment by stx** [comment]
Included in 13.7.
